### ISSUE TITLE
1.0.2 missing dist directory

### ISSUE THREAD

**Issue by palmtown** [absurdengineer/vue3-avatar#3]
Hello,

With the latest update to 1.0.3, an error is generatd "Can't resolve 'vue3-avatar' in..." this is because the npm install does not include the dist folder.  To make this package work, I have to force version 1.0.1.  Please fix, thanks!

**Comment by absurdengineer** [comment]
Hello,

Thank you for bringing this to my attention. I appreciate your prompt response and the information you provided about the issue. I have solved the issue and tested it myself. I'll make sure to include the necessary files in the npm package for future releases. Once again, thanks!
