### ISSUE TITLE
Add prop :customStyle

### ISSUE THREAD

**Issue by iviu23** [absurdengineer/vue3-avatar#4]
Hi @absurdengineer,

It would be really nice if you could add the `:customStyle` prop as in [vue-avatar](https://github.com/eliep/vue-avatar). I am migrating our app to Vue3, and being able to customize the font (along with any other CSS properties) is a must for us in order to match the current aesthetics of the UI.

Hope you can finally add it (since you already considered in this [closed issue](https://github.com/absurdengineer/vue3-avatar/issues/1)).

Thank you in advance.

**Comment by absurdengineer** [comment]
Hi there,

Apologies for the delay in responding! I’m excited to let you know that :customAvatarStyle and :customStatusStyle props have been implemented in vue3-avatar. You can now customize the avatar and status styles to fit the aesthetics of your UI seamlessly.

Thanks again for your patience, and I hope this will help!

Best regards,
Mohammad
